#!/usr/bin/env python3
"""Render measured flush profiling, recovery evidence and MySQL comparisons."""
import html,json,pathlib,re,statistics
ROOT=pathlib.Path(__file__).resolve().parents[1];V=ROOT/'validation'
A=V/'optimization-artifacts'
mysql=json.loads((V/'mysql-report.json').read_text())
crash=json.loads((V/'optimized-recovery.json').read_text())
recovery=json.loads((V/'mysql-storage-recovery.json').read_text())
assert mysql['complete'] and recovery['complete']
for key in ('local_SIGKILL_ext4_fsync','storage_engine_SIGKILL_postgres_amcheck','remote_scrub','remote_only_ext4_recovery','remote_only_postgres_amcheck'):assert crash['tests'][key]=='passed'
assert recovery['mysql']['infinidisk2-storage-recovery']['storage_engine_SIGKILL_recovery']=='passed'
summary={'postgres':{},'mysql':{}}
def med(a,key):return statistics.median(s[key] for s in a)
for label in ('paired-fsync','paired-fdatasync'):
    d=json.loads((A/'postgres'/f'optimization-{label}.json').read_text())
    p=d['postgres']['infinidisk2-'+label];assert p['database_SIGKILL_recovery']=='passed'
    lines=(A/'postgres'/f'infinidisk2-{label}-server.log').read_text().splitlines()
    statuses=[json.loads(m[0]) for m in [re.findall(r'\{"volume".*\}',l) for l in lines] if m]
    s=statuses[-1];groups=s['flush_groups']
    summary['postgres'][label]={'median_tps':med(p['samples'],'tps'),'samples':p['samples'],'wal_ms':s['wal_sync_ns']/groups/1e6,'watermark_ms':s['watermark_sync_ns']/groups/1e6,'flush_calls':s['flush_calls'],'flush_groups':groups}
gain=summary['postgres']['paired-fdatasync']['median_tps']/summary['postgres']['paired-fsync']['median_tps']-1
labels=('zerofs-durable','zerofs-async','infinidisk2','native')
rows=[];mdrows=[]
for workload in ('read_write','read_only','write_only'):
    values=[];summary['mysql'][workload]={}
    for label in labels:
        p=mysql['mysql'][label];assert p['database_SIGKILL_recovery']=='passed'
        a=p['samples'][workload];assert len(a)==3
        assert all(s['ignored_errors']==0 for s in a), (label,workload)
        v={'median_tps':med(a,'tps'),'min_tps':min(s['tps'] for s in a),'max_tps':max(s['tps'] for s in a),'median_p95_ms':med(a,'p95_ms'),'ignored_errors':sum(s['ignored_errors'] or 0 for s in a)}
        summary['mysql'][workload][label]=v
        values.append(f'{v["median_tps"]:.2f}<small>{v["min_tps"]:.2f}–{v["max_tps"]:.2f} ; p95 {v["median_p95_ms"]:.2f} ms</small>')
    rows.append('<tr><td>'+workload+'</td>'+''.join('<td>'+s+'</td>' for s in values)+'</tr>')
    mdrows.append('| '+workload+' | '+' | '.join(f'{summary["mysql"][workload][e]["median_tps"]:.2f}' for e in labels)+' |')
(V/'optimization-summary.json').write_text(json.dumps(summary,indent=2))
before=summary['postgres']['paired-fsync'];after=summary['postgres']['paired-fdatasync']
change='''Le chemin de FLUSH/FUA conserve deux barrières ordonnées : persister tous les segments WAL nécessaires, puis persister le watermark. File::sync_data remplace File::sync_all uniquement pour cette synchronisation des données et du watermark ; les créations de fichiers, fsync de répertoire, écritures atomiques et scellements conservent leur traitement des métadonnées. Le format disque ne change pas. sync_data_only=true est le défaut ; false conserve le chemin fsync initial pour comparaison. Les horodatages des fichiers internes ne participent pas à la récupération. fdatasync persiste aussi les métadonnées nécessaires à la lecture, dont la taille du fichier : on ne supprime pas la persistance des données ni une barrière.'''
profiling=f'''Sur pgbench scale 2, quatre clients, une CPU et 512 Mio pour PostgreSQL, moteur avec RAM 1 Gio/SSD 4 Gio : médiane fsync {before["median_tps"]:.2f} TPS, fdatasync {after["median_tps"]:.2f} TPS, soit +{gain*100:.1f} %. Trois échantillons de 15 secondes par mode, sur la même DB et le même binaire instrumenté ; fsync est testé avant fdatasync. Le watermark passe de {before["watermark_ms"]:.3f} à {after["watermark_ms"]:.3f} ms en moyenne par groupe ; le WAL de {before["wal_ms"]:.3f} à {after["wal_ms"]:.3f} ms. Le regroupement dans le moteur reste presque nul ({before["flush_calls"]} appels pour {before["flush_groups"]} groupes sur le passage fsync), donc ajouter une attente artificielle ne répond pas au goulot observé. Le correctif ultérieur de refus des barrières sur volume défaillant est présent dans le binaire des tests MySQL et de reprise finaux, mais n’était pas encore présent dans ce couple de mesures PostgreSQL. Ces temps viennent des compteurs cumulés du processus, au dernier statut périodique ; ils incluent les appels de préparation et checkpoint. La VM est partagée et les échantillons courts : le gain mesuré ne constitue pas une garantie universelle.'''
method='''MySQL Community 8.0.46, sysbench OLTP, quatre tables de 25 000 lignes, huit threads, seed 42, trois répétitions par charge avec cible de 15 secondes ; les transactions en cours peuvent allonger la fenêtre. Chaque conteneur dispose d’une CPU et 1 Gio ; buffer pool InnoDB 256 Mio. innodb_flush_log_at_trx_commit=1, sync_binlog=1, innodb_doublewrite=ON, innodb_flush_method=O_DIRECT et log_bin=1 vérifiés. Moteurs RAM 1 Gio et SSD 4 Gio, huit connexions NBD, ext4 noatime, volumes S3 UUID neufs. Échauffement read_only de 10 secondes. Les données tiennent dans le buffer pool : le read_only reflète surtout le CPU MySQL, pas une lecture froide S3. ZeroFS conserve sa compression LZ4 et son chiffrement applicatif ; InfiniDisk2 n’en implémente pas dans cette version. Cette différence fonctionnelle participe aux coûts mesurés. L'ordre est ZeroFS sans fsync, ZeroFS avec fsync sur la même DB, InfiniDisk2, puis disque natif. Les deux premiers partagent les mêmes données et cache disque ; les ordres ne sont pas randomisés.'''
durability='''ZeroFS durable publie S3 lors des barrières ; ZeroFS async ignore les FLUSH/FUA alors que MySQL affiche toujours ses paramètres de durabilité actifs. InfiniDisk2 persiste localement puis publie S3 de façon asynchrone. La référence native utilise ext4 sur le disque de la VM. Ces contrats diffèrent : les ratios ne prouvent pas une supériorité à durabilité S3 identique. La fenêtre de perte depuis S3 peut dépasser les cinq secondes configurées pendant un ralentissement ou une panne réseau.'''
checks='''Après chaque configuration MySQL : SIGKILL du processus DB, redémarrage, quatre comptes de lignes exactement égaux à 25 000 et CHECK TABLE EXTENDED OK. Pour InfiniDisk2, test supplémentaire de SIGKILL du moteur pendant sysbench read_write actif, arrêt forcé de MySQL, reprise ext4 par e2fsck, reprise InnoDB, comptes et CHECK TABLE corrects. La campagne PostgreSQL couvre également SIGKILL du moteur pendant transactions, fichier fsync identique, scrub distant et restauration sur nouveau répertoire local uniquement depuis S3. Aucune erreur sysbench ignorée sur les 36 échantillons MySQL. Ces tests concernent des crashs de processus ; une vraie panne électrique reste à tester.'''
safety='''La review du chemin d’erreur a aussi corrigé un cas où une barrière déjà en attente pouvait poursuivre après une défaillance du volume. La santé est revérifiée après acquisition du verrou de synchronisation ; une erreur/panique du worker de synchronisation rend le volume indisponible aux nouvelles écritures. Le test queued_barrier_rejects_acknowledgement_after_volume_failure vérifie le refus d’acquitter cette barrière et l’absence d’avancement du frontier durable. Onze tests unitaires et un test NBD FLUSH/FUA/multi-connexion passent ; clippy avec warnings interdits et rustfmt passent.'''
review='''L’optimisation réduit un coût précis sans changer le contrat de persistance. Le WAL reste la majorité du temps de synchronisation ; une future préallocation et un protocole de frontier durable dans le WAL pourraient réduire les coûts, avec migration et campagne de pannes nécessaires. Ne pas ajouter une temporisation de group commit sans preuve qu’il existe des barrières concurrentes à regrouper. MySQL read_write atteint 59 % du débit natif et write_only 23 % : l’écart en écriture reste important malgré le gain face à ZeroFS async. La priorité de performance est de profiler ce write_only et d’évaluer la préallocation du WAL sans supprimer une barrière. Priorité ensuite aux essais longues durées et données au-delà du buffer pool/cache, à la compaction des segments partiellement vivants et à l’index paginé. Le prototype n’est pas encore qualifié pour toutes les DB et tous les volumes.'''
md='# Optimisation des commits et benchmark MySQL\n\n'+change+'\n\n'+profiling+'\n\n## MySQL, médianes TPS\n\n| Charge | ZeroFS S3 | ZeroFS fsync ignoré | InfiniDisk2 local | Disque natif |\n|---|---:|---:|---:|---:|\n'+'\n'.join(mdrows)+'\n\n'+method+'\n\n'+durability+'\n\n## Contrôles de reprise\n\n'+checks+'\n\n'+safety+'\n\n## Review\n\n'+review+'\n\nSémantique de référence : [fsync/fdatasync, Linux man-pages](https://man7.org/linux/man-pages/man2/fsync.2.html). Résultats : ../validation/mysql-report.json, ../validation/optimized-recovery.json, ../validation/mysql-storage-recovery.json et ../validation/optimization-artifacts/.\n'
md+='\nReproduction sur la VM : `python3 scripts/compare_zerofs.py --mysql-only`, puis `python3 scripts/compare_zerofs.py --mysql-recovery-report <report.json> --engine infinidisk2 --phase-label mysql-crash`. La reprise S3 utilise `python3 scripts/validate_vm.py --s3 --credentials /opt/elestio/infinidisk/bench.env --postgres`. Les fichiers privés `*.secret` restent uniquement dans les dossiers de test de la VM ; les preuves exportées les excluent.\n'
(ROOT/'docs/optimisation-mysql.md').write_text(md)
css='body{font:16px/1.65 system-ui;background:#eef2f6;color:#172838;margin:0}main{max-width:1120px;margin:auto;padding:28px}section{background:white;padding:24px;margin:18px 0;border-radius:10px}table{width:100%;border-collapse:collapse;font-size:14px}td,th{text-align:left;padding:10px;border-bottom:1px solid #ddd}small{display:block;color:#5a6979}a{color:#056}'
page=f'<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>InfiniDisk2 : optimisation et MySQL</title><style>{css}</style><main><h1>InfiniDisk2 : commits durables et MySQL</h1>'
for title,body in [('Modification et garantie',change),('Profil et résultat PostgreSQL',profiling),('Protocole MySQL',method),('Contrats de durabilité',durability)]:page+=f'<section><h2>{title}</h2><p>{html.escape(body)}</p></section>'
page+='<section><h2>MySQL : médianes TPS et plages des trois répétitions</h2><div style="overflow:auto"><table><tr><th>Charge</th><th>ZeroFS S3</th><th>ZeroFS fsync ignoré</th><th>InfiniDisk2 local</th><th>Disque natif</th></tr>'+''.join(rows)+'</table></div></section>'
for title,body in [('Reprise et intégrité',checks),('Correction du chemin d’erreur',safety),('Review et prochaines priorités',review)]:page+=f'<section><h2>{title}</h2><p>{html.escape(body)}</p></section>'
page+='<section><h2>Preuves et sources</h2><p><a href="mysql-report.json">MySQL</a> · <a href="optimized-recovery.json">Reprise S3/PostgreSQL</a> · <a href="mysql-storage-recovery.json">Crash moteur avec MySQL</a> · <a href="optimization-summary.json">Synthèse numérique</a> · <a href="../docs/optimisation-mysql.md">Rapport Markdown</a> · <a href="https://man7.org/linux/man-pages/man2/fsync.2.html">fsync/fdatasync : Linux man-pages</a></p><p>Code et preuves : /opt/app/data/infinidisk2 ; copie VM : /root/infinidisk2.</p></section></main></html>'
(V/'optimisation-mysql.html').write_text(page)
print(V/'optimisation-mysql.html')
