#!/usr/bin/env python3
"""Render the WAL factorial experiment and a MySQL dataset larger than its caches."""
import argparse,html,json,pathlib,re,statistics
p=argparse.ArgumentParser();p.add_argument('--decision',required=True);a=p.parse_args()
ROOT=pathlib.Path(__file__).resolve().parents[1];V=ROOT/'validation';W=V/'wal-artifacts'/'mysql'
phases=['wal-baseline-a','wal-prealloc','wal-writev','wal-combined','wal-baseline-b']
rows=[];summary={'decision':a.decision,'phases':{}}
for phase in phases:
    d=json.loads((W/('optimization-'+phase+'.json')).read_text());v=d['mysql']['infinidisk2-'+phase]
    assert d['complete'] and v['database_SIGKILL_recovery']=='passed'
    assert not v['trace_engine']
    samples=v['samples']['write_only'];assert len(samples)==3 and all(isinstance(s['ignored_errors'],int) for s in samples)
    stats=[json.loads(x) for l in (W/('infinidisk2-'+phase+'-server.log')).read_text().splitlines() for x in re.findall(r'\{"volume".*\}',l)]
    last=stats[-1];n=last['flush_groups'];tps=[s['tps'] for s in samples]
    s={'tps':tps,'median_tps':statistics.median(tps),'wal_mean_ms':last['wal_sync_ns']/n/1e6,'watermark_mean_ms':last['watermark_sync_ns']/n/1e6,'binary_sha256':d['binary_sha256']['infinidisk2'],'ignored_errors':[x['ignored_errors'] for x in samples]}
    summary['phases'][phase]=s
    rows.append([phase,f"{s['median_tps']:.2f}",', '.join(str(x) for x in tps),f"{s['wal_mean_ms']:.3f}",f"{s['watermark_mean_ms']:.3f}"])
text='''Le WAL conserve IDWAL001 et sa taille logique : aucune migration des volumes. L’expérience teste writev (en-tête et charge utile en un appel, gestion des écritures partielles/EINTR/WriteZero) et fallocate KEEP_SIZE (réservation de blocs sans prolonger EOF). Les blocs réservés après EOF sont libérés par PUNCH_HOLE seulement au-delà du dernier bloc contenant des données, à la rotation et à la récupération. Les barrières WAL puis watermark, les contrôles CRC, FLUSH/FUA et publication S3 ne sont pas supprimés. Les erreurs d’écriture rendent toujours le volume indisponible.'''
method='''MySQL 8.0.46, même base de quatre tables de 25 000 lignes, huit threads, une CPU, 1 Gio de RAM, buffer pool 256 Mio. Moteur RAM 1 Gio/SSD 4 Gio, hot_wal_mib=0. InnoDB flush_log_at_trx_commit=1, doublewrite=ON, O_DIRECT, binlog actif et sync_binlog=1. Trois passages write_only de 15 secondes par mode, sans strace, dix secondes d’échauffement. Ordre : référence A, préallocation seule, writev seul, combinaison, référence B. Même binaire pour les cinq modes, mêmes données ; évolution des journaux et charge d’une VM partagée restent des facteurs de variance. Après chaque mode : SIGKILL MySQL, reprise, comptes de lignes et CHECK TABLE EXTENDED. Deux passages signalent chacun une erreur ignorée par sysbench (writev seul, passage 1 ; combinaison, passage 2). Les logs agrégés ne précisent pas le code SQL : ces passages restent présentés, sans être qualifiés de sans erreur. Les moyennes WAL/watermark viennent du dernier statut cumulatif du processus, préparation et reprise incluses.'''
profile='''Les strace agrégés sont des diagnostics distincts, exclus des résultats TPS. Le premier -c rapporte des temps CPU système ; le second -c -w rapporte des temps écoulés. Les attentes futex de plusieurs threads se cumulent et ne représentent ni un pourcentage de CPU consommé ni la durée réelle du benchmark. Le tracing réduit sensiblement le débit ; les compteurs internes et les passages sans tracing servent à juger les optimisations.'''
sections=[('Changement testé',text),('Décision',a.decision),('Méthode',method),('Interprétation du profil',profile)]
md='# InfiniDisk2 : expérience WAL et limites du cache MySQL\n\n'
for title,body in sections:md+='## '+title+'\n\n'+body+'\n\n'
md+='| Mode | Médiane TPS | Trois passages | WAL ms | Watermark ms |\n|---|---:|---|---:|---:|\n'+'\n'.join('| '+' | '.join(row)+' |' for row in rows)+'\n\n'
large=json.loads((V/'mysql-large-report.json').read_text());assert large['complete']
summary['large_mysql']={};large_rows=[]
for work in ('read_write','read_only','write_only'):
    values=[];summary['large_mysql'][work]={}
    for label in ('infinidisk2','native'):
        d=large['mysql'][label];assert d['database_SIGKILL_recovery'] in ('passed','passed_after_resume_larger_cache')
        samples=d['samples'][work];assert len(samples)==3 and all(s['ignored_errors']==0 for s in samples)
        t=[s['tps'] for s in samples];v={'median_tps':statistics.median(t),'samples':t,'median_p95_ms':statistics.median(s['p95_ms'] for s in samples)}
        summary['large_mysql'][work][label]=v;values.extend([f"{v['median_tps']:.2f} ({' → '.join(str(x) for x in t)})",f"{v['median_p95_ms']:.2f}"])
    large_rows.append([work,*values])
d=large['mysql']['infinidisk2'];footprint=d['table_file_bytes']/1024**2
large_text=f"Base neuve de quatre tables de {d['rows_per_table']:,} lignes, fichiers de tables {footprint:.1f} Mio. Buffer pool MySQL 256 Mio ; cache moteur RAM {large['memory_mib']} Mio et SSD {large['disk_mib']} Mio ; hot WAL désactivé. Volume {large['volume_size_bytes']/1024**3:.0f} Gio. Même limite CPU/MySQL et durabilité que le petit test ; distribution sysbench spéciale par défaut, seed 42, trois passages de 15 secondes. La taille dépasse les caches configurés, mais il ne s’agit pas d’un benchmark entièrement froid : le skew, les copies de pages entre caches et l’historique des lectures influencent le working set. La première vérification CHECK TABLE EXTENDED a dépassé 300 secondes sur le petit SSD ; la vérification a été reprise avec un SSD de cache de 2 Gio et une limite de 1 800 secondes. Les chiffres de débit proviennent exclusivement de la configuration initiale 128 Mio. La référence native utilise le même nombre de lignes, un buffer pool de 256 Mio et le disque ext4 de la VM. Préparation et reprise sont exclues du débit."
sections.append(('Base au-delà des caches',large_text));md+='## Base au-delà des caches\n\n'+large_text+'\n\n| Charge | InfiniDisk2 TPS | p95 ms | Natif TPS | p95 ms |\n|---|---:|---:|---:|---:|\n'+'\n'.join('| '+' | '.join(row)+' |' for row in large_rows)+'\n\n'
uniform_rows=[];summary['uniform_read_only']={}
for phase,engine in [('cache-uniform-small','infinidisk2'),('cache-uniform-large','infinidisk2'),('cache-uniform-page16','infinidisk2'),('cache-uniform-native','native')]:
    path=V/'wal-artifacts'/'mysql-large'/('optimization-'+phase+'.json')
    d=json.loads(path.read_text());v=d['mysql'][engine+'-'+phase]
    assert d['complete'] and v['random_distribution']=='uniform' and v['warmup_seconds']==60
    assert v['database_SIGKILL_recovery']=='not_run_read_only_repeat'
    t=v['samples']['read_only'];assert len(t)==3 and all(s['ignored_errors']==0 for s in t)
    result={'median_tps':statistics.median(s['tps'] for s in t),'samples':[s['tps'] for s in t],'median_p95_ms':statistics.median(s['p95_ms'] for s in t),'startup_seconds':v['startup_seconds'],'ssd_cache_bytes_before_samples':v.get('ssd_cache_bytes_before_samples')}
    summary['uniform_read_only'][phase]=result
    uniform_rows.append([phase,f"{result['median_tps']:.2f}",', '.join(str(s['tps']) for s in t),f"{result['median_p95_ms']:.2f}"])
uniform_text='Accès uniformes en lecture seule sur la même grande base vérifiée, huit threads, trois passages de 15 secondes et 60 secondes d’échauffement par configuration. InfiniDisk2 conserve 64 Mio de cache RAM ; le SSD passe de 128 Mio à 2 Gio. Un passage supplémentaire conserve 2 Gio de SSD et réduit les GET/cache extents de 64 à 16 Kio. Même fichier de volume, caches conservés, ordre petit SSD puis grand SSD puis natif : ce test montre un effet opérationnel du cache et de la chauffe, sans isoler tous les effets d’ordre. Le passage 16 Kio est effectué ensuite, avec le correctif de validation avant publication ; les fichiers du cache d’extents sont remis à zéro lors du changement de taille. Ces répétitions en lecture seule n’ajoutent pas de SIGKILL/CHECK TABLE ; le dataset avait déjà passé ces contrôles dans la campagne initiale. Les CRC sont toujours vérifiés sur les pages lues. Le natif utilise les mêmes paramètres MySQL et la même distribution uniforme.'
sections.append(('Accès uniformes et taille du SSD',uniform_text));md+='## Accès uniformes et taille du SSD\n\n'+uniform_text+'\n\n| Configuration | Médiane TPS | Trois passages | p95 ms |\n|---|---:|---|---:|\n'+'\n'.join('| '+' | '.join(row)+' |' for row in uniform_rows)+'\n\n'
ready=V/'wal-artifacts'/'mysql-large'/'infinidisk2-mysql-ready.log';restart=ready.with_name('infinidisk2-mysql-restart.log')
seconds=ready.stat().st_mtime-restart.stat().st_mtime
summary['large_initial_recovery_seconds_estimate']=seconds
summary['large_integrity_resume']=large['mysql']['infinidisk2'].get('integrity_resume')
recovery_text=f'Reprise après SIGKILL sur grande base/petit SSD : environ {seconds:.0f} secondes entre le retour de docker start et la dernière sonde ready, dérivées des horodatages des logs exportés. Le binlog lu pendant cette reprise faisait environ 780 Mo. Un profil strace agrégé de cinq secondes a été attaché pendant cette reprise, sans intervenir dans les mesures TPS. InnoDB seul avait terminé son initialisation en environ 45 secondes ; la durée complète est plus longue. Ce résultat montre que la taille du cache et la disponibilité locale des journaux sont des enjeux de performance de reprise.'
sections.append(('Temps de reprise de la grande base',recovery_text));md+='## Temps de reprise de la grande base\n\n'+recovery_text+'\n\n'
recovery=json.loads((V/'wal-recovery.json').read_text());assert recovery['tests']['remote_only_postgres_amcheck']=='passed'
mysql_crash=json.loads((V/'wal-mysql-crash.json').read_text());assert mysql_crash['mysql']['infinidisk2-storage-recovery']['storage_engine_SIGKILL_recovery']=='passed'
checks='''Les configurations expérimentales passent les tests de récupération après SIGKILL MySQL. La version finale passe aussi SIGKILL du moteur pendant transactions MySQL, récupération ext4/InnoDB, comptes et CHECK TABLE ; la campagne S3/PostgreSQL vérifie SIGKILL local, SIGKILL du moteur, CRC du fichier durable, scrub distant et récupération uniquement depuis S3 avec pg_amcheck. Ces résultats détectent des classes de corruption, sans constituer une preuve universelle. Panne électrique, fsync défaillant et campagnes longues restent à qualifier. La durabilité distante reste asynchrone : la cadence de checkpoint n’est pas une borne RPO.'''
sections.append(('Priorités recommandées','La priorité pour les DB est de garantir la présence locale du working set et des journaux de reprise : suivre les défauts de cache, dimensionner le SSD et évaluer un préchargement contrôlé des données récentes après publication. Le hot_wal est volontairement à zéro dans ces essais pour isoler les caches distants ; la configuration normale conserve par défaut 1 Gio de WAL récent. Pour les commits, l’hypothèse suivante à mesurer est un WAL de taille fixe dont les blocs ont déjà été initialisés : KEEP_SIZE ne supprime pas la croissance de la taille logique lors des append. fdatasync doit persister cette taille lorsqu’elle change. Une initialisation complète pourrait éviter une partie de cette synchronisation de métadonnées, mais exige un nouveau format local, une comptabilité physique correcte et des tests de pannes. Ce n’est pas un gain démontré par les essais actuels. Ne pas supprimer FLUSH/FUA ni la barrière du watermark pour gagner artificiellement des TPS.'));md+='## Priorités recommandées\n\n'+'La priorité pour les DB est de garantir la présence locale du working set et des journaux de reprise : suivre les défauts de cache, dimensionner le SSD et évaluer un préchargement contrôlé des données récentes après publication. Le hot_wal est volontairement à zéro dans ces essais pour isoler les caches distants ; la configuration normale conserve par défaut 1 Gio de WAL récent. Pour les commits, l’hypothèse suivante à mesurer est un WAL de taille fixe dont les blocs ont déjà été initialisés : KEEP_SIZE ne supprime pas la croissance de la taille logique lors des append. fdatasync doit persister cette taille lorsqu’elle change. Une initialisation complète pourrait éviter une partie de cette synchronisation de métadonnées, mais exige un nouveau format local, une comptabilité physique correcte et des tests de pannes. Ce n’est pas un gain démontré par les essais actuels. Ne pas supprimer FLUSH/FUA ni la barrière du watermark pour gagner artificiellement des TPS.'+'\n\n'
sections.append(('Correction d’intégrité avant publication','Un test a injecté une corruption dans un WAL local déjà synchronisé, avant le checkpoint. La version précédente publiait ce segment et avançait la racine distante ; le test échouait avant correction. La version finale vérifie sur le buffer exact envoyé l’identité du segment/volume, la longueur attendue, les formats et bornes des enregistrements, leurs CRC et la dernière séquence. Une erreur bloque les nouvelles écritures et empêche la publication de HEAD. Le test confirme que le checkpoint distant précédent reste récupérable. Quatorze tests unitaires et un test NBD passent, ainsi que rustfmt et clippy sans avertissement.'));md+='## Correction d’intégrité avant publication\n\n'+'Un test a injecté une corruption dans un WAL local déjà synchronisé, avant le checkpoint. La version précédente publiait ce segment et avançait la racine distante ; le test échouait avant correction. La version finale vérifie sur le buffer exact envoyé l’identité du segment/volume, la longueur attendue, les formats et bornes des enregistrements, leurs CRC et la dernière séquence. Une erreur bloque les nouvelles écritures et empêche la publication de HEAD. Le test confirme que le checkpoint distant précédent reste récupérable. Quatorze tests unitaires et un test NBD passent, ainsi que rustfmt et clippy sans avertissement.'+'\n\n'
sections.append(('Intégrité et limites',checks));md+='## Intégrité et limites\n\n'+checks+'\n\nRéférences : [fallocate](https://man7.org/linux/man-pages/man2/fallocate.2.html), [writev](https://man7.org/linux/man-pages/man2/writev.2.html), [fdatasync](https://man7.org/linux/man-pages/man2/fsync.2.html). Preuves : ../validation/wal-artifacts/, wal-recovery.json, wal-mysql-crash.json, mysql-large-report.json et wal-build-manifest.json.\n'
final=json.loads((V/'wal-final-build-manifest.json').read_text())
assert recovery['binary_sha256']==final['binary_sha256']
assert mysql_crash['binary_sha256']['infinidisk2']==final['binary_sha256']
post=json.loads((W/'optimization-wal-post-validation.json').read_text())
v=post['mysql']['infinidisk2-wal-post-validation']
assert post['complete'] and v['database_SIGKILL_recovery']=='passed'
assert post['binary_sha256']['infinidisk2']==final['binary_sha256']
t=[s['tps'] for s in v['samples']['write_only']];assert len(t)==3 and all(s['ignored_errors']==0 for s in v['samples']['write_only'])
summary['post_publication_validation']={'samples':t,'median_tps':statistics.median(t),'binary_sha256':final['binary_sha256']}
post_text=f"Les cinq essais factoriels et les premiers passages de cache utilisent le binaire de191e1d (13 tests), avant cette correction. Le passage 16 Kio et les reprises finales utilisent le binaire {final['binary_sha256'][:8]} (14 tests). Sur le petit dataset, le binaire final confirme write_only à {statistics.median(t):.2f} TPS, avec les trois passages {t}, sans gain net établi par rapport aux références. Les manifestes historiques et finaux sont distincts ; ce résultat ne qualifie pas toutes les DB ni tous les profils de volume."
sections.append(('Chronologie et confirmation du binaire final',post_text));md+='## Chronologie et confirmation du binaire final\n\n'+post_text+'\n\n'
md+='Reproduction : `python3 scripts/compare_zerofs.py --mysql-only --engine infinidisk2 --mysql-rows 1000000 --mysql-volume-gib 4 --mysql-memory-cache-mib 64 --mysql-disk-cache-mib 128`. Les accès uniformes utilisent `--mysql-repeat-report <report.json> --phase-label <label> --engine infinidisk2 --mysql-workloads read_only --mysql-rand-type uniform --mysql-warm-seconds 60 --mysql-repeat-disk-cache-mib 2048 --mysql-skip-crash-check`. Les sources exactes des runners récents sont archivées dans les preuves.\n'
(ROOT/'docs/optimisation-wal.md').write_text(md)
(V/'wal-summary.json').write_text(json.dumps(summary,indent=2)+'\n')
def table(headers,rows):return '<div style="overflow:auto"><table><tr>'+''.join('<th>'+html.escape(x)+'</th>' for x in headers)+'</tr>'+''.join('<tr>'+''.join('<td>'+html.escape(x)+'</td>' for x in row)+'</tr>' for row in rows)+'</table></div>'
css='body{margin:0;background:#eef2f6;color:#182838;font:16px/1.6 system-ui}main{max-width:1100px;margin:auto;padding:25px}section{background:white;padding:22px;border-radius:10px;margin:18px 0}td,th{padding:10px;text-align:left;border-bottom:1px solid #ddd}table{width:100%;font-size:14px}a{color:#056}'
page='<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>InfiniDisk2 : WAL et MySQL au-delà du cache</title><style>'+css+'</style><main><h1>WAL et MySQL au-delà du cache</h1>'
for title,body in sections:page+='<section><h2>'+title+'</h2><p>'+html.escape(body)+'</p></section>'
page+='<section><h2>Expérience WAL</h2>'+table(['Mode','Médiane TPS','Trois passages','WAL ms','Watermark ms'],rows)+'</section>'
page+='<section><h2>Base plus grande</h2>'+table(['Charge','InfiniDisk2 TPS','p95 ms','Natif TPS','p95 ms'],large_rows)+'</section>'
page+='<section><h2>Lectures uniformes</h2>'+table(['Configuration','Médiane TPS','Trois passages','p95 ms'],uniform_rows)+'</section>'
page+='<section><h2>Preuves</h2><a href="wal-summary.json">Synthèse</a> · <a href="mysql-large-report.json">MySQL grande base</a> · <a href="wal-recovery.json">Reprise S3</a> · <a href="wal-mysql-crash.json">Crash moteur MySQL</a> · <a href="wal-build-manifest.json">Binaire des expériences</a> · <a href="wal-final-build-manifest.json">Binaire final</a> · <a href="wal-publication-regression-before.log">Régression avant correction</a> · <a href="../docs/optimisation-wal.md">Rapport Markdown</a> · <a href="https://man7.org/linux/man-pages/man2/fallocate.2.html">fallocate</a> · <a href="https://man7.org/linux/man-pages/man2/writev.2.html">writev</a> · <a href="https://man7.org/linux/man-pages/man2/fsync.2.html">fdatasync</a></section></main></html>'
(V/'optimisation-wal.html').write_text(page);print(V/'optimisation-wal.html')
